/**
 * Created by wenbo.kuang on 2018/4/25.
 */
export const FETCH_START = "LEAD_READING/FETCH_START";
export const FETCH_SUCCESS = "LEAD_READING/FETCH_SUCCESS";
export const FETCH_ERROR = "LEAD_READING/FETCH_ERROR";
export const FETCH_END = "LEAD_READING/FETCH_END";
export const FETCH_CARD_LIST = "LEAD_READING/FETCH_CARD_LIST";