/**
 * Created by wenbo.kuang on 2018/4/25.
 */
export const FETCH_START = "DETAIL_PAGE/FETCH_START";
export const FETCH_SUCCESS = "DETAIL_PAGE/FETCH_SUCCESS";
export const FETCH_ERROR = "DETAIL_PAGE/FETCH_ERROR";
export const FETCH_END = "DETAIL_PAGE/FETCH_END";
export const FETCH_ARTICLE = "DETAIL_PAGE/FETCH_ARTICLE";